apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: b2b-newstore-theme
  annotations:
    github.com/project-slug: vtex-apps/b2b-newstore-theme
    backstage.io/techdocs-ref: dir:./
    vtex.com/application-id: TIL0JR6E
spec:
  system: b2b-suite
  type: frontend-ui
  lifecycle: maintenance
  owner: te-0010